### Preprocessing

In [6]:
import pandas as pd

In [7]:
filmList = pd.read_csv('data/ml-20m/movies.csv')
filmList

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [8]:
filmList['year'] = [x[-5:-1] for x in list(filmList['title'])]
filmList['title'] = [x[:-7].strip() for x in list(filmList['title'])]
filmList

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995
...,...,...,...,...
27273,131254,Kein Bund für's Leben,Comedy,2007
27274,131256,"Feuer, Eis & Dosenbier",Comedy,2002
27275,131258,The Pirates,Adventure,2014
27276,131260,Rentun Ruusu,(no genres listed),2001
27277,131262,Innocence,Adventure|Fantasy|Horror,2014

In [9]:
setToDelete = set(filmList['year'])
for i in range(1891, 2016):
    setToDelete.discard(str(i))
setToDelete = list(setToDelete)

In [10]:
filmList['filter'] = filmList['year'].isin(setToDelete)
filmList = filmList.drop(filmList[filmList['filter']].index)
filmList['year'] = [int(x) for x in list(filmList['year'])]

In [11]:
filmList2 = pd.read_csv('data/moviesList2/movies.csv')
filmList2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [12]:
filmList2 = filmList2.rename(columns={'name':'title'})
filmList2

,title,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [13]:
movies = filmList.merge(filmList2, on=['title', 'year'])
movies

,movieId,title,genres,year,filter,rating,genre,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,False,G,Animation,"November 22, 1995 (United States)",8.3,913000.0,John Lasseter,John Lasseter,Tom Hanks,United States,30000000.0,394436586.0,Walt Disney Pictures,81.0
1,2,Jumanji,Adventure|Children|Fantasy,1995,False,PG,Adventure,"December 15, 1995 (United States)",7.0,318000.0,Joe Johnston,Jonathan Hensleigh,Robin Williams,United States,65000000.0,262821940.0,TriStar Pictures,104.0
2,3,Grumpier Old Men,Comedy|Romance,1995,False,PG-13,Comedy,"December 22, 1995 (United States)",6.7,25000.0,Howard Deutch,Mark Steven Johnson,Walter Matthau,United States,25000000.0,71518503.0,Lancaster Gate,101.0
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,False,R,Comedy,"December 22, 1995 (United States)",6.0,10000.0,Forest Whitaker,Terry McMillan,Whitney Houston,United States,16000000.0,81452156.0,Twentieth Century Fox,124.0
4,5,Father of the Bride Part II,Comedy,1995,False,PG,Comedy,"December 8, 1995 (United States)",6.1,36000.0,Charles Shyer,Albert Hackett,Steve Martin,United States,30000000.0,76594107.0,Sandollar Productions,106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4397,130520,Home,Animation|Children|Comedy|Fantasy|Sci-Fi,2015,False,PG,Animation,"March 27, 2015 (United States)",6.6,95000.0,Tim Johnson,Tom J. Astle,Jim Parsons,United States,135000000.0,386041607.0,DreamWorks Animation,94.0
4398,130578,The Gunman,Action|Thriller,2015,False,R,Action,"March 20, 2015 (United States)",5.8,40000.0,Pierre Morel,Jean-Patrick Manchette,Sean Penn,United States,40000000.0,24177137.0,Open Road Films (II),115.0
4399,130746,Bolero,Drama|Romance,1984,False,R,Comedy,"August 31, 1984 (United States)",3.0,5100.0,John Derek,John Derek,Bo Derek,United States,7000000.0,8914881.0,City Films,105.0
4400,130804,The Fourth War,Drama|Thriller,1990,False,R,Drama,"March 23, 1990 (United States)",5.6,1400.0,John Frankenheimer,Stephen Peters,Roy Scheider,United States,NaN,1305887.0,Kodiak Films,91.0
4401,131013,Get Hard,Comedy,2015,False,R,Comedy,"March 27, 2015 (United States)",6.0,127000.0,Etan Cohen,Jay Martel,Will Ferrell,United States,40000000.0,111711453.0,Gary Sanchez Productions,100.0

In [14]:
movies = movies.drop(columns=['filter', 'rating', 'released', 'score', 'votes', 'score', 'budget', 'gross', 'runtime'])
movies

,movieId,title,genres,year,genre,director,writer,star,country,company
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,Animation,John Lasseter,John Lasseter,Tom Hanks,United States,Walt Disney Pictures
1,2,Jumanji,Adventure|Children|Fantasy,1995,Adventure,Joe Johnston,Jonathan Hensleigh,Robin Williams,United States,TriStar Pictures
2,3,Grumpier Old Men,Comedy|Romance,1995,Comedy,Howard Deutch,Mark Steven Johnson,Walter Matthau,United States,Lancaster Gate
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,Comedy,Forest Whitaker,Terry McMillan,Whitney Houston,United States,Twentieth Century Fox
4,5,Father of the Bride Part II,Comedy,1995,Comedy,Charles Shyer,Albert Hackett,Steve Martin,United States,Sandollar Productions
...,...,...,...,...,...,...,...,...,...,...
4397,130520,Home,Animation|Children|Comedy|Fantasy|Sci-Fi,2015,Animation,Tim Johnson,Tom J. Astle,Jim Parsons,United States,DreamWorks Animation
4398,130578,The Gunman,Action|Thriller,2015,Action,Pierre Morel,Jean-Patrick Manchette,Sean Penn,United States,Open Road Films (II)
4399,130746,Bolero,Drama|Romance,1984,Comedy,John Derek,John Derek,Bo Derek,United States,City Films
4400,130804,The Fourth War,Drama|Thriller,1990,Drama,John Frankenheimer,Stephen Peters,Roy Scheider,United States,Kodiak Films
4401,131013,Get Hard,Comedy,2015,Comedy,Etan Cohen,Jay Martel,Will Ferrell,United States,Gary Sanchez Productions

In [15]:
anotherList = pd.read_csv('data/moviesList1/filmtv_movies.csv')
anotherList

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [16]:
anotherList = anotherList.drop(columns=['filmtv_id', 'duration', 'avg_vote', 'critics_vote', 'public_vote', 'description', 'notes', 'total_votes'])
anotherList

,title,year,genre,country,directors,actors,humor,rhythm,effort,tension,erotism
0,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,United States,"David Detiege, Art Davis, Bill Perez",NaN,3,3,0,0,0
1,18 anni tra una settimana,1991,Drama,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",0,2,0,2,0
2,Ride a Wild Pony,1976,Romantic,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",1,2,1,0,0
3,Diner,1982,Comedy,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",2,2,0,1,2
4,A che servono questi quattrini?,1942,Comedy,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
41394,Gold Digger Killer,2021,Thriller,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",0,0,0,0,0
41395,Addio al nubilato 2,2023,Comedy,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",0,0,0,0,0
41396,Konferensen,2023,Horror,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",0,0,0,0,0
41397,Ballelina,2023,Thriller,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",0,0,0,0,0
41398,Invitación a un Asesinato,2023,Thriller,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",0,0,0,0,0

In [17]:
movies = movies.merge(anotherList, on=['title', 'year'])
movies

,movieId,title,genres,year,genre_x,director,writer,star,country_x,company,genre_y,country_y,directors,actors,humor,rhythm,effort,tension,erotism
0,2,Jumanji,Adventure|Children|Fantasy,1995,Adventure,Joe Johnston,Jonathan Hensleigh,Robin Williams,United States,TriStar Pictures,Fantasy,United States,Joe Johnston,"Robin Williams, Kirsten Dunst, Bradley Pierce,...",2,3,1,2,0
1,3,Grumpier Old Men,Comedy|Romance,1995,Comedy,Howard Deutch,Mark Steven Johnson,Walter Matthau,United States,Lancaster Gate,Comedy,United States,Howard Deutch,"Jack Lemmon, Walter Matthau, Sophia Loren, Ann...",2,3,0,1,1
2,4,Waiting to Exhale,Comedy|Drama|Romance,1995,Comedy,Forest Whitaker,Terry McMillan,Whitney Houston,United States,Twentieth Century Fox,Comedy,United States,Forest Whitaker,"Whitney Houston, Angela Bassett, Loretta Devin...",2,2,0,0,1
3,5,Father of the Bride Part II,Comedy,1995,Comedy,Charles Shyer,Albert Hackett,Steve Martin,United States,Sandollar Productions,Comedy,United States,Charles Shyer,"Steve Martin, Diane Keaton, Martin Short, Kimb...",2,2,0,1,0
4,6,Heat,Action|Crime|Thriller,1995,Crime,Michael Mann,Michael Mann,Al Pacino,United States,Warner Bros.,Noir,United States,Michael Mann,"Al Pacino, Robert De Niro, Val Kilmer, Jon Voi...",1,3,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,130204,Patty Hearst,(no genres listed),1988,Biography,Paul Schrader,Patricia Hearst,Natasha Richardson,United Kingdom,Atlantic Entertainment Group,Drama,"United States, Great Britain",Paul Schrader,"Natasha Richardson, William Forsythe, Ving Rha...",0,2,1,0,0
3464,130520,Home,Animation|Children|Comedy|Fantasy|Sci-Fi,2015,Animation,Tim Johnson,Tom J. Astle,Jim Parsons,United States,DreamWorks Animation,Animation,United States,Tim Johnson,NaN,2,1,0,0,0
3465,130578,The Gunman,Action|Thriller,2015,Action,Pierre Morel,Jean-Patrick Manchette,Sean Penn,United States,Open Road Films (II),Action,"United States, France, Spain",Pierre Morel,"Sean Penn, Idris Elba, Javier Bardem, Ray Wins...",1,2,2,2,0
3466,130746,Bolero,Drama|Romance,1984,Comedy,John Derek,John Derek,Bo Derek,United States,City Films,Drama,United States,John Derek,"Bo Derek, Andrea Occhipinti, Ana Obregon; Geor...",0,0,0,0,0
3467,131013,Get Hard,Comedy,2015,Comedy,Etan Cohen,Jay Martel,Will Ferrell,United States,Gary Sanchez Productions,Comedy,United States,Etan Cohen,"Will Ferrell, Kevin Hart, Craig T. Nelson, Ali...",2,2,1,1,1

In [18]:
movies = movies.drop(columns=['genre_x', 'genre_y'])
movies = movies.drop(columns=['country_x', 'directors'])
movies = movies.rename(columns={'country_y':'country'})
movies

,movieId,title,genres,year,director,writer,star,company,country,actors,humor,rhythm,effort,tension,erotism
0,2,Jumanji,Adventure|Children|Fantasy,1995,Joe Johnston,Jonathan Hensleigh,Robin Williams,TriStar Pictures,United States,"Robin Williams, Kirsten Dunst, Bradley Pierce,...",2,3,1,2,0
1,3,Grumpier Old Men,Comedy|Romance,1995,Howard Deutch,Mark Steven Johnson,Walter Matthau,Lancaster Gate,United States,"Jack Lemmon, Walter Matthau, Sophia Loren, Ann...",2,3,0,1,1
2,4,Waiting to Exhale,Comedy|Drama|Romance,1995,Forest Whitaker,Terry McMillan,Whitney Houston,Twentieth Century Fox,United States,"Whitney Houston, Angela Bassett, Loretta Devin...",2,2,0,0,1
3,5,Father of the Bride Part II,Comedy,1995,Charles Shyer,Albert Hackett,Steve Martin,Sandollar Productions,United States,"Steve Martin, Diane Keaton, Martin Short, Kimb...",2,2,0,1,0
4,6,Heat,Action|Crime|Thriller,1995,Michael Mann,Michael Mann,Al Pacino,Warner Bros.,United States,"Al Pacino, Robert De Niro, Val Kilmer, Jon Voi...",1,3,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,130204,Patty Hearst,(no genres listed),1988,Paul Schrader,Patricia Hearst,Natasha Richardson,Atlantic Entertainment Group,"United States, Great Britain","Natasha Richardson, William Forsythe, Ving Rha...",0,2,1,0,0
3464,130520,Home,Animation|Children|Comedy|Fantasy|Sci-Fi,2015,Tim Johnson,Tom J. Astle,Jim Parsons,DreamWorks Animation,United States,NaN,2,1,0,0,0
3465,130578,The Gunman,Action|Thriller,2015,Pierre Morel,Jean-Patrick Manchette,Sean Penn,Open Road Films (II),"United States, France, Spain","Sean Penn, Idris Elba, Javier Bardem, Ray Wins...",1,2,2,2,0
3466,130746,Bolero,Drama|Romance,1984,John Derek,John Derek,Bo Derek,City Films,United States,"Bo Derek, Andrea Occhipinti, Ana Obregon; Geor...",0,0,0,0,0
3467,131013,Get Hard,Comedy,2015,Etan Cohen,Jay Martel,Will Ferrell,Gary Sanchez Productions,United States,"Will Ferrell, Kevin Hart, Craig T. Nelson, Ali...",2,2,1,1,1

In [19]:
f = open( 'item_index2entity_id.txt', 'w' )
for id, entity in movies.iterrows():
    f.write(str(entity['movieId']) + '\t' + str(id) + '\n')

In [20]:
f = open( 'ids_with_names.txt', 'w' )
for id, entity in movies.iterrows():
    f.write(str(entity['movieId']) + '\t' + str(id) + '\t' + str(entity['title'] + '\n'))

In [21]:
movies

,movieId,title,genres,year,director,writer,star,company,country,actors,humor,rhythm,effort,tension,erotism
0,2,Jumanji,Adventure|Children|Fantasy,1995,Joe Johnston,Jonathan Hensleigh,Robin Williams,TriStar Pictures,United States,"Robin Williams, Kirsten Dunst, Bradley Pierce,...",2,3,1,2,0
1,3,Grumpier Old Men,Comedy|Romance,1995,Howard Deutch,Mark Steven Johnson,Walter Matthau,Lancaster Gate,United States,"Jack Lemmon, Walter Matthau, Sophia Loren, Ann...",2,3,0,1,1
2,4,Waiting to Exhale,Comedy|Drama|Romance,1995,Forest Whitaker,Terry McMillan,Whitney Houston,Twentieth Century Fox,United States,"Whitney Houston, Angela Bassett, Loretta Devin...",2,2,0,0,1
3,5,Father of the Bride Part II,Comedy,1995,Charles Shyer,Albert Hackett,Steve Martin,Sandollar Productions,United States,"Steve Martin, Diane Keaton, Martin Short, Kimb...",2,2,0,1,0
4,6,Heat,Action|Crime|Thriller,1995,Michael Mann,Michael Mann,Al Pacino,Warner Bros.,United States,"Al Pacino, Robert De Niro, Val Kilmer, Jon Voi...",1,3,2,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,130204,Patty Hearst,(no genres listed),1988,Paul Schrader,Patricia Hearst,Natasha Richardson,Atlantic Entertainment Group,"United States, Great Britain","Natasha Richardson, William Forsythe, Ving Rha...",0,2,1,0,0
3464,130520,Home,Animation|Children|Comedy|Fantasy|Sci-Fi,2015,Tim Johnson,Tom J. Astle,Jim Parsons,DreamWorks Animation,United States,NaN,2,1,0,0,0
3465,130578,The Gunman,Action|Thriller,2015,Pierre Morel,Jean-Patrick Manchette,Sean Penn,Open Road Films (II),"United States, France, Spain","Sean Penn, Idris Elba, Javier Bardem, Ray Wins...",1,2,2,2,0
3466,130746,Bolero,Drama|Romance,1984,John Derek,John Derek,Bo Derek,City Films,United States,"Bo Derek, Andrea Occhipinti, Ana Obregon; Geor...",0,0,0,0,0
3467,131013,Get Hard,Comedy,2015,Etan Cohen,Jay Martel,Will Ferrell,Gary Sanchez Productions,United States,"Will Ferrell, Kevin Hart, Craig T. Nelson, Ali...",2,2,1,1,1

In [22]:
stats = set(list(movies['humor']))
print(stats)
stats = set(list(movies['rhythm']))
print(stats)
stats = set(list(movies['effort']))
print(stats)
stats = set(list(movies['tension']))
print(stats)
stats = set(list(movies['erotism']))
print(stats)

{0, 1, 2, 3, 4}
{0, 1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5}
{0, 1, 2, 3, 4}

In [23]:
info = {'genre': 0, 'year': 1, 'director': 2, 'writer': 3, 'star': 4, 'company': 5, 'country': 6, 'actor': 7, 'humor': 8, 'rhythm': 9, 'effort': 10, 'tension': 11, 'erotism': 12}

In [24]:
entity_counter = len(movies)
entity_dict = {}
stats = {
    'humor': {0: entity_counter, 1: entity_counter + 1, 2: entity_counter + 2, 3: entity_counter + 3, 4: entity_counter + 4},
    'rhythm': {0: entity_counter + 5, 1: entity_counter + 6, 2: entity_counter + 7, 3: entity_counter + 8, 4: entity_counter + 9, 5: entity_counter + 10},
    'effort': {0: entity_counter + 11, 1: entity_counter + 12, 2: entity_counter + 13, 3: entity_counter + 14, 4: entity_counter + 15, 5: entity_counter + 16},
    'tension': {0: entity_counter + 17, 1: entity_counter + 18, 2: entity_counter + 19, 3: entity_counter + 20, 4: entity_counter + 21, 5: entity_counter + 22},
    'erotism': {0: entity_counter + 23, 1: entity_counter + 24, 2: entity_counter + 25, 3: entity_counter + 26, 4: entity_counter + 27}
}
entity_counter += 28

In [25]:
f = open( 'kg_final.txt', 'w' )
for index, row in movies.iterrows():
    #genres
    genreList = row['genres'].split('|')
    for genre in genreList:
        
        if genre == '(no genres listed)':
            continue
        
        if genre not in entity_dict.keys():
            entity_dict[genre] = entity_counter
            entity_counter += 1
        f.write(str(index) + '\t' + '0' + '\t' + str(entity_dict[genre]) + '\n')
    
    #year
    if str(row['year']) not in entity_dict.keys():
        entity_dict[str(row['year'])] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '1' + '\t' + str(entity_dict[str(row['year'])]) + '\n')
    
    #director
    if row['director'] not in entity_dict.keys():
        entity_dict[row['director']] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '2' + '\t' + str(entity_dict[row['director']]) + '\n')
    
    #writer
    if row['writer'] not in entity_dict.keys():
        entity_dict[row['writer']] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '3' + '\t' + str(entity_dict[row['writer']]) + '\n')
    
    #star #4
    if row['star'] not in entity_dict.keys():
        entity_dict[row['star']] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '4' + '\t' + str(entity_dict[row['star']]) + '\n')
    
    #company #5
    if row['company'] not in entity_dict.keys():
        entity_dict[row['company']] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '5' + '\t' + str(entity_dict[row['company']]) + '\n')
    
    #country #6
    if row['country'] not in entity_dict.keys():
        entity_dict[row['country']] = entity_counter
        entity_counter += 1
    f.write(str(index) + '\t' + '6' + '\t' + str(entity_dict[row['country']]) + '\n')
    
    #actors #7
    if type(row['actors']) != float:
        actorList = row['actors'].split(', ')
        for actor in actorList:
            if actor not in entity_dict.keys():
                entity_dict[actor] = entity_counter
                entity_counter += 1
            f.write(str(index) + '\t' + '7' + '\t' + str(entity_dict[actor]) + '\n')
    
    #humor 8
    f.write(str(index) + '\t' + '8' + '\t' + str(stats['humor'][row['humor']]) + '\n')
    
    #rhythm 9
    f.write(str(index) + '\t' + '9' + '\t' + str(stats['rhythm'][row['rhythm']]) + '\n')
    
    #effort 10
    f.write(str(index) + '\t' + '10' + '\t' + str(stats['effort'][row['effort']]) + '\n')
    
    #tension 11
    f.write(str(index) + '\t' + '11' + '\t' + str(stats['tension'][row['tension']]) + '\n')
    
    #erotism 12
    f.write(str(index) + '\t' + '12' + '\t' + str(stats['erotism'][row['erotism']]) + '\n')
    

#print(entity_dict)

### ratings

In [26]:
rates = pd.read_csv('data/ml-20m/ratings.csv')
rates

          userId  movieId  rating   timestamp
0              1        2     3.5  1112486027
1              1       29     3.5  1112484676
2              1       32     3.5  1112484819
3              1       47     3.5  1112484727
4              1       50     3.5  1112484580
...          ...      ...     ...         ...
20000258  138493    68954     4.5  1258126920
20000259  138493    69526     4.5  1259865108
20000260  138493    69644     3.0  1260209457
20000261  138493    70286     5.0  1258126944
20000262  138493    71619     2.5  1255811136

[20000263 rows x 4 columns]

In [27]:
idMapper = {}
for index, row in movies.iterrows():
    idMapper[row['movieId']] = index

In [28]:
movieSet = set(movies['movieId'])
f = open( 'ratings_final.txt', 'w' )

userSet = set()

for index, row in rates.iterrows():
    if row['movieId'] in movieSet:
        userSet.add(row['userId'] - 1)
    if row['movieId'] in movieSet:
        f.write(str(int(row['userId'] - 1)) + '\t' + str(int(idMapper[row['movieId']])) + '\t' + ('1' if row['rating'] >= 4. else '0') + '\n')

In [30]:
for i in range(max(rates['userId']) + 2):
    if i not in userSet:
        print(i)

476
12240
13448
19659
19800
21624
23913
29166
32245
32925
40298
40431
48286
49764
59146
62142
65869
66644
73253
75347
77243
80656
82533
86875
104782
114456
117948
125427
127202
127230
128157
138493
138494